server:
  port: 9007
spring:
  application:
    name: cloud-search
  data:
    elasticsearch:
      clusterâ€nodes: 192.168.2.2:9300
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.2:6868/eureka
  instance:
    prefer-ip-address: true